plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
}

version = property('mod_version')
group = property('mod_group_id')
base { archivesName = property('mod_id') }

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

repositories { mavenCentral() }

minecraft {
    mappings channel: property('mapping_channel'), version: property('mapping_version')
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods { faketimemod { source sourceSets.main } }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods { faketimemod { source sourceSets.main } }
        }
    }
}

mixin {
    add sourceSets.main, 'faketimemod.refmap.json'
    config 'faketimemod.mixins.json'
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test { useJUnitPlatform() }

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/mods.toml') {
        expand project.properties
    }
}
